import * as React from "react";
import { supabase } from "@/integrations/supabase/client";

type Language = "en" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, values?: Record<string, string | number>) => string;
}

const translations = {
  en: {
    // App
    "app.title": "Beat",
    "app.tagline": "Keep Your Beat Strong",
    
    // Header
    "header.insights": "Insights",
    "header.family": "Family",
    "header.coach": "AI Coach",
    "header.signOut": "Sign Out",
    "header.language": "Language",
    "header.theme": "Theme",
    "header.english": "English",
    "header.hindi": "Hindi",
    "header.light": "Light",
    "header.dark": "Dark",
    "header.system": "System",
    "header.viewProfile": "View Profile",
    "header.completeProfile": "Complete your profile",
    "header.quickActions": "Quick Actions",
    "header.restartTutorial": "Restart Tutorial",
    "header.connectFitnessTrackers": "Connect Fitness Trackers",
    
    // Accessibility
    "accessibility.textSize": "Text Size",
    "accessibility.normal": "Normal",
    "accessibility.large": "Large",
    
    // Dashboard
    "dashboard.goodMorning": "Good Morning",
    "dashboard.goodAfternoon": "Good Afternoon",
    "dashboard.goodEvening": "Good Evening",
    "dashboard.tagline": "Let's keep your beat strong today.",
    "dashboard.todaysRituals": "Today's Rituals",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.viewTrends": "View Trends",
    "dashboard.familyDashboard": "Family Dashboard",
    "dashboard.aiCopilot": "Beat AI",
    "dashboard.daysStrong": "Days Strong",
    "dashboard.quickAccess": "Quick Access",
    "dashboard.achievements": "Achievements",
    "dashboard.medications": "Medications",
    "dashboard.shop": "Shop",
    "dashboard.challenges": "Challenges",
    "dashboard.premium": "Premium",
    
    // Rituals
    "ritual.morning": "Morning Ritual",
    "ritual.evening": "Evening Ritual",
    "ritual.morningSubtitle": "With chai ☕",
    "ritual.eveningSubtitle": "After dinner 🍽️",
    "ritual.bloodPressure": "Blood Pressure",
    "ritual.fastingSugar": "Fasting Sugar",
    "ritual.sleepQuality": "Sleep Quality",
    "ritual.medsTaken": "Meds Taken",
    "ritual.randomSugar": "Random Sugar",
    "ritual.stepsCount": "Steps Count",
    "ritual.stressLevel": "Stress Level",
    "ritual.startRitual": "Start Ritual",
    "ritual.completed": "Completed",
    "ritual.eveningComingSoon": "Evening ritual coming soon!",
    
    // HeartScore
    "heartScore.title": "Your HeartScore",
    "heartScore.excellent": "Excellent!",
    "heartScore.good": "Good progress",
    "heartScore.needsWork": "Needs attention",
    "heartScore.aiExplanation": "What moved your score today",
    
    // Checkin
    "checkin.step": "Step",
    "checkin.of": "of",
    "checkin.bloodPressure": "Blood Pressure",
    "checkin.enterMorningBP": "Enter your morning BP reading",
    "checkin.enterEveningBP": "Enter your evening BP reading",
    "checkin.systolic": "Systolic (Top)",
    "checkin.diastolic": "Diastolic (Bottom)",
    "checkin.mmHg": "mmHg",
    "checkin.fastingSugar": "Fasting Sugar",
    "checkin.randomSugar": "Random Sugar",
    "checkin.enterSugar": "Enter your sugar level",
    "checkin.mgdL": "mg/dL",
    "checkin.optional": "Optional",
    "checkin.sleepQuality": "Sleep Quality",
    "checkin.howDidYouSleep": "How did you sleep last night?",
    "checkin.veryPoor": "Very Poor",
    "checkin.poor": "Poor",
    "checkin.fair": "Fair",
    "checkin.good": "Good",
    "checkin.excellent": "Excellent",
    "checkin.medications": "Medications",
    "checkin.didYouTakeMeds": "Did you take your prescribed medications?",
    "checkin.yes": "Yes",
    "checkin.no": "No",
    "checkin.stepsCount": "Steps Count",
    "checkin.enterSteps": "Enter your steps count for today",
    "checkin.steps": "steps",
    "checkin.stressLevel": "Stress Level",
    "checkin.howStressed": "How stressed do you feel?",
    "checkin.low": "Low",
    "checkin.moderate": "Moderate",
    "checkin.high": "High",
    "checkin.veryHigh": "Very High",
    "checkin.next": "Next",
    "checkin.back": "Back",
    "checkin.complete": "Complete Ritual",
    "checkin.completedSuccess": "Ritual completed!",
    "checkin.startMorning": "Start Morning Check-in",
    "checkin.startEvening": "Start Evening Check-in",
    "checkin.readingAutoFilled": "Reading auto-filled!",
    "checkin.morningComplete": "Morning check-in complete! 🎉",
    "checkin.eveningComplete": "Evening check-in complete! 🎉",
    "checkin.failed": "Check-in failed",
    "checkin.saveFailed": "Failed to save data. Please try again.",
    "checkin.sugarRangeError": "Sugar reading must be between 20 and 600 mg/dL",
    "checkin.stepsRangeError": "Steps count must be between 0 and 100,000",
    "checkin.autoFillPhoto": "Auto-fill from Photo",
    "checkin.bpPhotoHelp": "Take a photo of your BP monitor",
    "checkin.orManual": "or enter manually",
    "checkin.systolicShort": "Systolic",
    "checkin.diastolicShort": "Diastolic",
    "checkin.heartRateOptional": "Heart Rate (optional)",
    "checkin.fastingBloodSugar": "Fasting Blood Sugar",
    "checkin.scan": "Scan",
    "checkin.sleepQuestion": "How did you sleep?",
    "checkin.feelingQuestion": "How are you feeling?",
    "checkin.socialConnection": "Social Connection",
    "checkin.connectedQuestion": "How connected do you feel?",
    "checkin.talkedQuestion": "Did you talk to family or friends?",
    "checkin.lonelyQuestion": "Feeling lonely?",
    "checkin.outsideQuestion": "Did you step outside today?",
    "checkin.morningMedsQuestion": "Morning medications?",
    "checkin.eveningMedsQuestion": "Evening medications?",
    "checkin.notYet": "Not yet",
    "checkin.notesToday": "Any notes for today?",
    "checkin.notesTodaySubtitle": "Optional - add any thoughts",
    "checkin.notesTodayPlaceholder": "How are you feeling today?",
    "checkin.notesDay": "Any notes about your day?",
    "checkin.notesDaySubtitle": "Optional - reflect on your day",
    "checkin.notesDayPlaceholder": "How was your day?",
    "checkin.morningTitle": "Morning Check-in",
    "checkin.eveningTitle": "Evening Check-in",
    "checkin.enterBpOptional": "Enter your BP reading (optional)",
    "checkin.enterSugarOptional": "Enter your sugar reading (optional)",
    "checkin.lonelyNotAtAll": "Not at all",
    "checkin.lonelyALittle": "A little",
    "checkin.lonelySomewhat": "Somewhat",
    "checkin.lonelyVery": "Very",
    "checkin.tryAgain": "Please try again.",
    
    // AI Coach
    "coach.title": "Beat AI",
    "coach.subtitle": "Your medical-grade AI health coach",
    "coach.placeholder": "Ask me anything about your health...",
    "coach.send": "Send",
    "coach.thinking": "Thinking...",
    "coach.newChat": "New Chat",
    "coach.disclaimer": "This is AI guidance, not medical diagnosis. Consult a doctor for serious symptoms.",
    "coach.hello": "Hello! I'm Beat",
    "coach.askAnything": "Ask me anything about your health. I'm here to help.",
    
    // Common
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.close": "Close",
    "common.success": "Success!",
    "common.error": "Something went wrong",
    "common.retry": "Retry",
    "common.remove": "Remove",
    "common.saving": "Saving...",
    "common.user": "User",
    "common.premium": "Premium",
    "common.days": "days",
    "common.reviews": "reviews",
    "common.skip": "Skip",
    "common.reset": "Reset",
    
    // Family
    "family.title": "Family Dashboard",
    "family.subtitle": "Keep track of your loved ones' health",
    "family.addMember": "Add Family Member",
    "family.noMembers": "No Family Members Yet",
    "family.addFirst": "Add Your First Member",
    "family.relationship": "Relationship",
    "family.permissions": "Permissions",
    "family.canView": "Can View Health Data",
    "family.canNudge": "Can Send Nudges",
    
    // Onboarding
    "onboarding.welcome": "Welcome to Beat!",
    "onboarding.subtitle": "Keep Your Beat Strong",
    "onboarding.language": "Choose your language",
    "onboarding.continue": "Continue",
    "onboarding.basicInfo": "Basic Information",
    "onboarding.basicInfoDesc": "Tell us about yourself",
    "onboarding.fullName": "Full Name",
    "onboarding.namePlaceholder": "Enter your name",
    "onboarding.dateOfBirth": "Date of Birth",
    "onboarding.gender": "Gender",
    "onboarding.genderPlaceholder": "Select gender",
    "onboarding.male": "Male",
    "onboarding.female": "Female",
    "onboarding.other": "Other",
    "onboarding.height": "Height (cm)",
    "onboarding.weight": "Weight (kg)",
    "onboarding.healthGoals": "Health Goals",
    "onboarding.healthGoalsDesc": "What would you like to track?",
    "onboarding.hasHypertension": "I have high blood pressure",
    "onboarding.hasDiabetes": "I have diabetes",
    "onboarding.hasHeartDisease": "I have heart disease",
    "onboarding.ritualTimes": "Daily Check-in Times",
    "onboarding.ritualTimesDesc": "When should we remind you?",
    "onboarding.morningTime": "Morning Check-in",
    "onboarding.eveningTime": "Evening Check-in",
    "onboarding.finish": "Get Started",
    "onboarding.success": "Welcome to Beat!",
    "onboarding.error": "Failed to complete onboarding",
    
    // Insights
    "insights.title": "Health Insights",
    "insights.subtitle": "Track your health trends and patterns",
    "insights.pdfReport": "PDF Report",
    "insights.avgBP": "Avg BP",
    "insights.avgSugar": "Avg Sugar",
    "insights.heartScore": "HeartScore",
    "insights.avgSteps": "Avg Steps",
    "insights.aiInsights": "AI Health Insights",
    "insights.personalized": "Personalized analysis based on your health data",
    "insights.heartScoreTrend": "HeartScore Trend (30 Days)",
    "insights.bpTrend": "Blood Pressure Trend (30 Days)",
    "insights.sugarTrend": "Blood Sugar Trend (30 Days)",
    "insights.emptyHeartScore": "Complete rituals to see your HeartScore trends",
    "insights.emptyBp": "Log BP readings to see trends",
    "insights.emptySugar": "Log sugar levels to see trends",
    
    // Challenges
    "challenges.title": "Health Challenges",
    "challenges.subtitle": "Build healthy habits together with the community",
    "challenges.featured": "Featured Challenges",
    "challenges.myChallenges": "My Challenges",
    "challenges.allChallenges": "All Challenges",
    "challenges.join": "Join",
    "challenges.leave": "Leave",
    "challenges.joined": "Joined",
    "challenges.daysLeft": "days left",
    "challenges.participants": "participants",
    
    // Shop
    "shop.title": "Health Store",
    "shop.subtitle": "Recommended products for your health journey",
    "shop.featured": "Featured Products",
    "shop.viewProduct": "View Product",
    "shop.beatShop": "Beat Shop",
    "shop.beatRecommended": "Health products recommended by Beat",
    "shop.buy": "Buy",
    "shop.membersDiscount": "Beat Premium members get exclusive discounts. Upgrade today!",
    "shop.viewPremium": "View Premium →",
    "shop.badge.bestSeller": "Best Seller",
    "shop.badge.popular": "Popular",
    "shop.badge.heartHealth": "Heart Health",
    "shop.badge.topRated": "Top Rated",
    
    // Subscription
    "subscription.title": "Beat Premium",
    "subscription.subtitle": "Unlock your full health potential",
    "subscription.free": "Free",
    "subscription.basic": "Basic",
    "subscription.premium": "Premium",
    "subscription.currentPlan": "Current Plan",
    "subscription.upgrade": "Upgrade",
    "subscription.perMonth": "/month",
    
    // Profile
    "profile.title": "Profile",
    "profile.settings": "Settings",
    "profile.notifications": "Notifications",
    "profile.connectDevices": "Connect Devices",
    "profile.exportData": "Export My Data",
    "profile.deleteAccount": "Delete Account",
    "profile.signOut": "Sign Out",
    "profile.backToDashboard": "Back to Dashboard",
    "profile.personalInfo": "Personal Information",
    "profile.fullName": "Full Name",
    "profile.phoneNumber": "Phone Number",
    "profile.weight": "Weight (kg)",
    "profile.height": "Height (cm)",
    "profile.dateOfBirth": "Date of Birth",
    "profile.gender": "Gender",
    "profile.preferNotToSay": "Prefer not to say",
    "profile.female": "Female",
    "profile.male": "Male",
    "profile.nonBinary": "Non-binary",
    "profile.other": "Other",
    "profile.healthConditions": "Health Conditions",
    "profile.diabetes": "Diabetes",
    "profile.hypertension": "Hypertension",
    "profile.heartDisease": "Heart Disease",
    "profile.advancedMetrics": "Advanced Health Metrics (Optional)",
    "profile.smokingStatus": "Smoking Status",
    "profile.unknown": "Unknown",
    "profile.neverSmoked": "Never Smoked",
    "profile.formerSmoker": "Former Smoker",
    "profile.currentSmoker": "Current Smoker",
    "profile.cholesterolRatio": "Cholesterol Ratio",
    "profile.lastHba1c": "Last HbA1c (%)",
    "profile.advancedMetricsHelp": "These metrics improve AI risk predictions. Ask your doctor for these values.",
    "profile.notificationPreferences": "Notification Preferences",
    "profile.whatsappMessages": "WhatsApp Messages",
    "profile.whatsappMessagesDesc": "Daily reminders via WhatsApp",
    "profile.dailyReminders": "Daily Reminders",
    "profile.dailyRemindersDesc": "Morning and evening check-in reminders",
    "profile.weeklySummary": "Weekly Summary",
    "profile.weeklySummaryDesc": "Weekly health insights report",
    "profile.upgradeToPremium": "Upgrade to Premium",
    "profile.premiumDescription": "Unlock Beat AI Coach, PDF reports, advanced insights, and priority support.",
    "profile.upgradePremiumPrice": "Upgrade to Premium - ₹199/month",
    "profile.dataPrivacy": "Data & Privacy",
    "profile.exportingData": "Exporting Data...",
    "profile.exportDialogTitle": "Export your Beat Health data?",
    "profile.exportDialogDescription": "This creates a JSON file containing your profile, BP logs, sugar logs, check-in behavior logs, and medications. On Android, Beat will open the native share sheet so you can save the file to Files, Drive, Gmail, or another app. In a browser, a download named beat-health-data-[date].json will start.",
    "profile.startExport": "Start Export",
    "profile.exporting": "Exporting...",
    "profile.exportFailed": "Export failed",
    "profile.retryExport": "Retry Export",
    "profile.deleteConfirmTitle": "Are you absolutely sure?",
    "profile.deleteConfirmDescription": "This action cannot be undone. This will permanently delete your account and remove all your health data from our servers.",
    "profile.deleteAccountAction": "Delete Account",
    "profile.saveChanges": "Save Changes",
    "profile.namePlaceholder": "Enter your name",
    "profile.saved": "Profile saved successfully",
    "profile.saveFailed": "Failed to save profile",
    "profile.loadFailed": "Failed to load profile",
    "profile.photoUpdated": "Profile photo updated",
    "profile.photoUploadFailed": "Failed to upload photo",
    "profile.fileTooLarge": "File size must be less than 2MB",
    "profile.exportPreparing": "Preparing your JSON export...",
    "profile.exportSignInRequired": "You need to be signed in to export your data.",
    "profile.exportOpeningShare": "Opening share sheet for your JSON export...",
    "profile.exportShareTitle": "Beat Health Data Export",
    "profile.exportShareText": "Your Beat Health data export is attached as a JSON file.",
    "profile.exportShareDialog": "Save or share your data export",
    "profile.exportNativeSuccess": "Your data export is ready. Choose Files, Drive, Gmail, or another app in the share sheet to save it.",
    "profile.exportBrowserSuccess": "Your data has been exported successfully. Browser download started as a JSON file.",
    "profile.exportDismissed": "Export prepared, but the share sheet was dismissed. Start export again to save or share the JSON file.",
    "profile.exportFailedTryAgain": "Failed to export data. Please try again.",
    "profile.noActiveSession": "No active session found",
    "profile.accountDeleted": "Account deleted successfully",
    "profile.deleteFailed": "Failed to delete account",
    
    // Medications
    "medications.title": "Medications",
    "medications.subtitle": "Manage your medications and track adherence",
    "medications.loading": "Loading medications...",
    "medications.add": "Add Medication",
    "medications.addNew": "Add New Medication",
    "medications.name": "Medication Name *",
    "medications.namePlaceholder": "e.g., Aspirin",
    "medications.dosage": "Dosage",
    "medications.dosagePlaceholder": "e.g., 100mg",
    "medications.frequency": "Frequency",
    "medications.morningOnly": "Morning Only",
    "medications.eveningOnly": "Evening Only",
    "medications.morningEvening": "Morning & Evening",
    "medications.notes": "Notes",
    "medications.notesPlaceholder": "Any special instructions",
    "medications.adherenceRate": "Adherence Rate (Last 7 Days)",
    "medications.takenOnTime": "medications taken on time",
    "medications.noMedications": "No medications added yet",
    "medications.addFirst": "Add Your First Medication",
    "medications.taken": "Taken",
    "medications.skip": "Skip",
    "medications.takenToday": "Taken Today",
    "medications.dosagePrefix": "Dosage:",
    "medications.frequencyPrefix": "Frequency:",
    "medications.morning": "Morning",
    "medications.evening": "Evening",
    "medications.adherenceProgress": "{taken} of {total} medications taken on time",
    
    // Dashboard details
    "dashboard.startMorningCheckin": "Start Morning Check-in",
    "dashboard.startEveningCheckin": "Start Evening Check-in",
    "dashboard.smartCapture": "Smart Capture",
    "dashboard.healthMonitoring": "Health Monitoring",
    
    // Bottom navigation
    "nav.health": "Health",
    "nav.beat": "Beat",
    "nav.me": "Me",
    
    // Activity tracker
    "activity.title": "Activity Tracker",
    "activity.subtitle": "Track your movement and earn health points",
    "activity.todayProgress": "Today's Progress",
    "activity.goalProgress": "{percent}% of goal",
    "activity.steps": "Steps",
    "activity.calories": "Calories",
    "activity.minutes": "Minutes",
    "activity.active": "Active",
    "activity.paused": "Paused",
    "activity.pause": "Pause",
    "activity.resume": "Resume",
    "activity.endSave": "End & Save",
    "activity.startActivity": "Start an Activity",
    "activity.walking": "Walking",
    "activity.running": "Running",
    "activity.cycling": "Cycling",
    "activity.yoga": "Yoga",
    "activity.started": "{activity} session started!",
    "activity.saved": "Activity saved!",
    "activity.saveFailed": "Failed to save activity",
    "activity.motionNote": "📱 Step counting works best on mobile devices with motion sensors",
    "activity.tipsTitle": "💡 Activity Tips",
    "activity.tipSteps": "• 10,000 steps ≈ 5 miles ≈ 400-500 calories",
    "activity.tipBp": "• Walking 30 min daily can lower BP by 4-9 mmHg",
    "activity.tipSugar": "• Post-meal walks help reduce blood sugar spikes",

    // Social wellness
    "social.title": "Social Wellness",
    "social.log": "Log",
    "social.logTitle": "Log Social Activity",
    "social.interactionsToday": "Today's interactions",
    "social.moodToday": "How's your mood today?",
    "social.connectedScale": "How connected do you feel? (1 = Lonely, 5 = Very Connected)",
    "social.outsideToday": "Did you go outside today?",
    "social.notesOptional": "Notes (optional)",
    "social.notesPlaceholder": "How was your day?",
    "social.interactions": "Interactions",
    "social.daysOut": "Days Out",
    "social.wellness": "Wellness",
    "social.loggedToday": "Today logged!",
    "social.notLoggedToday": "Haven't logged today yet",
    "social.suggested": "Suggested activities:",
    "social.logged": "Social wellness logged!",
    "social.logFailed": "Failed to log",
    "social.familyCall": "Family Call",
    "social.friendVisit": "Friend Visit",
    "social.communityEvent": "Community Event",
    "social.religiousGathering": "Temple/Mosque/Church",
    "social.neighborChat": "Neighbor Chat",
    "social.videoCall": "Video Call",
    "mood.low": "Low",
    "mood.belowAverage": "Below Average",
    "mood.neutral": "Neutral",
    "mood.good": "Good",
    "mood.great": "Great",

    // Alerts
    "alerts.title": "Health Alerts",
    "alerts.new": "new",
    "alerts.allClear": "All Clear!",
    "alerts.none": "No health alerts at the moment. Keep up the good work!",
    "alerts.newAlerts": "New Alerts",
    "alerts.urgent": "Urgent",
    "alerts.important": "Important",
    "alerts.info": "Info",
    "alerts.acknowledged": "Alert acknowledged",
    "alerts.ackFailed": "Failed to acknowledge alert",
    "alerts.justNow": "Just now",
    "alerts.yesterday": "Yesterday",
    "alerts.highBp": "High BP",
    "alerts.lowBp": "Low BP",
    "alerts.highSugar": "High Sugar",
    "alerts.lowSugar": "Low Sugar",
    "alerts.rapidChange": "Rapid Change",
    "alerts.missedCheckin": "Missed Check-in",
    "alerts.medicationDue": "Medication Due",

    // Family permissions
    "family.managePermissions": "Manage Permissions",
    "family.updatePermissions": "Update relationship and permissions for {name}",
    "family.selectRelationship": "Select relationship",
    "family.parent": "Parent",
    "family.child": "Child",
    "family.spouse": "Spouse",
    "family.sibling": "Sibling",
    "family.grandparent": "Grandparent",
    "family.grandchild": "Grandchild",
    "family.other": "Other",
    "family.accessPermissions": "Access Permissions",
    "family.viewHealthData": "View Health Data",
    "family.viewHealthDesc": "Allow viewing BP, sugar, medications, and health metrics",
    "family.sendReminders": "Send Reminders",
    "family.sendRemindersDesc": "Allow sending health reminders and check-in nudges",
    "family.privacyNotice": "Privacy Notice:",
    "family.privacyNoticeText": "Family members can only view data, not modify it. All access is logged for security.",

    // Agent settings/memory
    "agent.settings": "Agent Settings",
    "agent.settingsDesc": "Control how your AI agent behaves",
    "agent.autonomyLevel": "Autonomy Level",
    "agent.minimal": "Minimal",
    "agent.balanced": "Balanced",
    "agent.full": "Full",
    "agent.minimalDesc": "Agent observes only, no automatic actions",
    "agent.balancedDesc": "Nudges & celebrations, no goal changes",
    "agent.fullDesc": "Full autonomy including goal adjustments",
    "agent.automaticActions": "Automatic Actions",
    "agent.autoNudges": "Auto Nudges",
    "agent.autoNudgesDesc": "Proactive health reminders",
    "agent.autoCelebrations": "Auto Celebrations",
    "agent.autoCelebrationsDesc": "Automatic achievement recognition",
    "agent.autoGoalAdjustment": "Auto Goal Adjustment",
    "agent.autoGoalAdjustmentDesc": "Automatically adjust goals based on progress",
    "agent.healthAlerts": "Health Alerts",
    "agent.healthAlertsDesc": "Escalate concerning health patterns",
    "agent.dailyLimits": "Daily Limits",
    "agent.maxNudgesPerDay": "Max nudges per day",
    "agent.maxGoalAdjustmentsPerWeek": "Max goal adjustments per week",
    "agent.quietHours": "Quiet Hours",
    "agent.quietHoursDesc": "Agent won't send non-urgent notifications during quiet hours",
    "agent.from": "From",
    "agent.to": "To",
    "agent.preferencesSaved": "Agent preferences saved",
    "agent.preferencesFailed": "Failed to save preferences",
    "agent.memory": "Agent Memory",
    "agent.memoryDesc": "What Beat remembers about you",
    "agent.memories": "memories",
    "agent.engagementRate": "Engagement Rate",
    "agent.engaged": "Engaged",
    "agent.ignored": "Ignored",
    "agent.avgResponse": "Avg Response",
    "agent.whatBeatKnows": "What Beat Knows",
    "agent.memoryCleared": "Memory cleared",
    "agent.memoryClearFailed": "Failed to clear memory",
    "agent.primaryFocus": "Your primary focus is {focus} tracking",
    "agent.activeAround": "You're most active around {time}",
    "agent.engagementRateText": "Your engagement rate is {rate}%",
    "agent.nudgeFrequencyReduced": "We've reduced nudge frequency based on your preferences",
    "agent.learnedPreferences": "Learned Preferences",
    "agent.detectedPatterns": "Detected Patterns",
    "agent.knownFacts": "Known Facts",
    "agent.confident": "confident",
    "agent.clearMemoryTitle": "Clear this memory?",
    "agent.clearPatternTitle": "Clear this pattern?",
    "agent.clearFactTitle": "Clear this fact?",
    "agent.clearMemoryDesc": "Beat will forget \"{memory}\" and may re-learn it over time.",
    "agent.clearPatternDesc": "Beat will forget this pattern and may re-learn it over time.",
    "agent.clearFactDesc": "Beat will forget this fact and may re-learn it over time.",
    "agent.clear": "Clear",
    "agent.stillLearning": "Beat is still learning about you.",
    "agent.stillLearningDesc": "Use the app for a few days and patterns will emerge.",
    "devices.connectedDevices": "Connected Devices",
    "devices.addDevice": "Add Device",
    "devices.addNewDevice": "Add New Device",
    "devices.deviceType": "Device Type",
    "devices.selectDeviceType": "Select device type",
    "devices.deviceNameOptional": "Device Name (Optional)",
    "devices.deviceNamePlaceholder": "e.g., Omron BP Monitor, Ultrahuman CGM",
    "devices.noDevices": "No devices connected",
    "devices.noDevicesDesc": "Add your BP monitor, glucometer, or smartwatch to auto-sync readings.",
    "devices.connected": "Connected",
    "devices.pending": "Pending",
    "devices.neverSynced": "Never synced",
    "devices.justNow": "Just now",
    "devices.minutesAgo": "{count}m ago",
    "devices.hoursAgo": "{count}h ago",
    "devices.comingSoon": "Coming soon:",
    "devices.comingSoonDesc": "Auto-sync with Health Connect (Android) and Apple Health (iOS). For now, mark devices as \"connected\" after pairing, and use manual entry.",
    "devices.loadFailed": "Failed to load connected devices",
    "devices.selectTypeError": "Please select a device type",
    "devices.added": "Device added! Mark as connected once paired.",
    "devices.addFailed": "Failed to add device",
    "devices.connectedToast": "Device connected!",
    "devices.disconnectedToast": "Device disconnected",
    "devices.updateFailed": "Failed to update device",
    "devices.connectFirst": "Connect the device first",
    "devices.syncComplete": "Sync complete! Data imported.",
    "devices.syncFailed": "Sync failed",
    "devices.removed": "Device removed",
    "devices.removeFailed": "Failed to remove device",
    "devices.healthConnect": "Health Connect (Android)",
    "devices.appleHealth": "Apple Health (iOS)",
    "devices.smartwatch": "Smartwatch / Band",
    "devices.bpMonitor": "BP Monitor",
    "devices.glucometer": "Glucometer",
    "devices.cgm": "CGM Device",
    "devices.manualEntry": "Manual Entry",
    "labs.title": "Lab Results",
    "labs.add": "Add",
    "labs.addResult": "Add Lab Result",
    "labs.testType": "Test Type",
    "labs.selectTest": "Select test",
    "labs.testDate": "Test Date",
    "labs.value": "Value",
    "labs.normal": "Normal",
    "labs.labNameOptional": "Lab Name (Optional)",
    "labs.labNamePlaceholder": "e.g., Apollo Diagnostics",
    "labs.saveResult": "Save Result",
    "labs.testsDueSoon": "Tests Due Soon",
    "labs.daysOverdue": "{count} days overdue",
    "labs.inDays": "in {count} days",
    "labs.noResultsYet": "No results yet",
    "labs.outsideNormalRange": "Outside normal range",
    "labs.noLabResults": "No lab results yet",
    "labs.noLabResultsDesc": "Add your first result to start tracking",
    "labs.resultAdded": "Lab result added",
    "labs.addFailed": "Failed to add result",
    
    // HeartScore explanation
    "heartScore.infoAria": "How is HeartScore calculated?",
    "heartScore.infoTitle": "How is HeartScore calculated?",
    "heartScore.infoIntro": "Your HeartScore is calculated using your daily health habits and measurements.",
    "heartScore.factorsTitle": "It considers factors such as:",
    "heartScore.factorBp": "• Blood Pressure",
    "heartScore.factorSugar": "• Blood Sugar",
    "heartScore.factorCheckins": "• Daily Check-ins & Consistency",
    "heartScore.factorSleep": "• Sleep & Lifestyle habits",
    "heartScore.factorSocial": "• Social Well-being",
    "heartScore.factorEnvironment": "• Environmental factors (when available)",
    "heartScore.factorCognitive": "• Cognitive assessments (when available)",
    "heartScore.infoUpdates": "The score updates as new health data is recorded.",
    "heartScore.infoMissing": "Missing health data may reduce score accuracy.",
    "heartScore.infoHigher": "A higher score generally indicates healthier daily habits.",
    "heartScore.infoMedical": "The score is meant to help track trends over time and should not replace medical advice.",
    "heartScore.improveTitle": "Improve your HeartScore by:",
    "heartScore.improveCheckins": "✓ Completing daily check-ins",
    "heartScore.improveLogs": "✓ Logging BP and Sugar regularly",
    "heartScore.improveHabits": "✓ Following healthy lifestyle habits",
    "heartScore.snapshot": "Today's health snapshot",
    "heartScore.fair": "Fair",
    "heartScore.critical": "Critical",
    "heartScore.bp": "BP",
    "heartScore.sugar": "Sugar",
    "heartScore.ritual": "Ritual",
    "heartScore.completeRitual": "Complete a ritual to calculate your HeartScore",
    "heartScore.calculate": "Calculate Score",
    "heartScore.calculating": "Calculating...",
    
    // Device capture / OCR
    "deviceCapture.smartCapture": "Smart Capture",
    "deviceCapture.scanBp": "Scan BP",
    "deviceCapture.scanSugar": "Scan Sugar",
    "deviceCapture.heartRate": "Heart Rate",
    "deviceCapture.scanDeviceScreen": "Scan Device Screen",
    "deviceCapture.loginFirst": "Please log in first",
    "deviceCapture.saveFailed": "Failed to save reading",
    "deviceCapture.bpSaved": "BP {value} saved!",
    "deviceCapture.sugarSaved": "Blood sugar {value} mg/dL saved!",
    "deviceCapture.hrRecorded": "Heart rate {value} bpm recorded!",
    "deviceCapture.scanDevice": "Scan Device",
    "deviceCapture.bpMonitor": "BP Monitor",
    "deviceCapture.glucoseMeter": "Glucose Meter",
    "deviceCapture.pulseOximeter": "Pulse Oximeter",
    "deviceCapture.anyDevice": "Any Device",
    "deviceCapture.fileTooLarge": "File too large (max 10MB)",
    "deviceCapture.photoReadFailed": "Could not read the photo. Please take another photo and try again.",
    "deviceCapture.unableToRead": "Unable to read the {device}. Please take a clearer photo and try again.",
    "deviceCapture.detectedReading": "Detected Reading",
    "deviceCapture.confidence": "Confidence",
    "deviceCapture.retry": "Retry",
    "deviceCapture.useThis": "Use This",
    "deviceCapture.openCamera": "Open Camera",
    "deviceCapture.scanTitle": "Scan {device}",
    "deviceCapture.scanDescription": "Take a photo of the device screen",
    "deviceCapture.noReadings": "No readings detected",
    "deviceCapture.readingSaved": "Reading saved!",
  },
  hi: {
    // App
    "app.title": "बीट",
    "app.tagline": "अपना बीट मजबूत रखें",
    
    // Header
    "header.insights": "जानकारी",
    "header.family": "परिवार",
    "header.coach": "AI सहायक",
    "header.signOut": "साइन आउट",
    "header.language": "भाषा",
    "header.theme": "थीम",
    "header.english": "English",
    "header.hindi": "हिंदी",
    "header.light": "लाइट",
    "header.dark": "डार्क",
    "header.system": "सिस्टम",
    "header.viewProfile": "प्रोफ़ाइल देखें",
    "header.completeProfile": "अपनी प्रोफ़ाइल पूरी करें",
    "header.quickActions": "त्वरित कार्य",
    "header.restartTutorial": "ट्यूटोरियल फिर शुरू करें",
    "header.connectFitnessTrackers": "फिटनेस ट्रैकर कनेक्ट करें",
    
    // Accessibility
    "accessibility.textSize": "टेक्स्ट साइज़",
    "accessibility.normal": "सामान्य",
    "accessibility.large": "बड़ा",
    
    // Dashboard
    "dashboard.goodMorning": "सुप्रभात",
    "dashboard.goodAfternoon": "नमस्ते",
    "dashboard.goodEvening": "शुभ संध्या",
    "dashboard.tagline": "आइए आज अपने दिल को मजबूत रखें।",
    "dashboard.todaysRituals": "आज की दिनचर्या",
    "dashboard.quickActions": "त्वरित कार्य",
    "dashboard.viewTrends": "रुझान देखें",
    "dashboard.familyDashboard": "परिवार डैशबोर्ड",
    "dashboard.aiCopilot": "बीट AI",
    "dashboard.daysStrong": "दिन मजबूत",
    "dashboard.quickAccess": "त्वरित पहुंच",
    "dashboard.achievements": "उपलब्धियां",
    "dashboard.medications": "दवाइयां",
    "dashboard.shop": "शॉप",
    "dashboard.challenges": "चुनौतियां",
    "dashboard.premium": "प्रीमियम",
    
    // Rituals
    "ritual.morning": "सुबह की दिनचर्या",
    "ritual.evening": "शाम की दिनचर्या",
    "ritual.morningSubtitle": "चाय के साथ ☕",
    "ritual.eveningSubtitle": "रात के खाने के बाद 🍽️",
    "ritual.bloodPressure": "रक्तचाप",
    "ritual.fastingSugar": "खाली पेट शुगर",
    "ritual.sleepQuality": "नींद की गुणवत्ता",
    "ritual.medsTaken": "दवाई ली",
    "ritual.randomSugar": "रैंडम शुगर",
    "ritual.stepsCount": "कदमों की गिनती",
    "ritual.stressLevel": "तनाव का स्तर",
    "ritual.startRitual": "शुरू करें",
    "ritual.completed": "पूरा हुआ",
    "ritual.eveningComingSoon": "शाम की दिनचर्या जल्द आ रही है!",
    
    // HeartScore
    "heartScore.title": "आपका हार्टस्कोर",
    "heartScore.excellent": "बहुत बढ़िया!",
    "heartScore.good": "अच्छी प्रगति",
    "heartScore.needsWork": "ध्यान देने की जरूरत",
    "heartScore.aiExplanation": "आज आपके स्कोर में क्या बदलाव आया",
    
    // Checkin
    "checkin.step": "चरण",
    "checkin.of": "में से",
    "checkin.bloodPressure": "रक्तचाप",
    "checkin.enterMorningBP": "अपनी सुबह की BP रीडिंग दर्ज करें",
    "checkin.enterEveningBP": "अपनी शाम की BP रीडिंग दर्ज करें",
    "checkin.systolic": "सिस्टोलिक (ऊपर)",
    "checkin.diastolic": "डायस्टोलिक (नीचे)",
    "checkin.mmHg": "mmHg",
    "checkin.fastingSugar": "खाली पेट शुगर",
    "checkin.randomSugar": "रैंडम शुगर",
    "checkin.enterSugar": "अपनी शुगर का स्तर दर्ज करें",
    "checkin.mgdL": "mg/dL",
    "checkin.optional": "वैकल्पिक",
    "checkin.sleepQuality": "नींद की गुणवत्ता",
    "checkin.howDidYouSleep": "कल रात आपकी नींद कैसी रही?",
    "checkin.veryPoor": "बहुत खराब",
    "checkin.poor": "खराब",
    "checkin.fair": "ठीक",
    "checkin.good": "अच्छी",
    "checkin.excellent": "बेहतरीन",
    "checkin.medications": "दवाइयां",
    "checkin.didYouTakeMeds": "क्या आपने अपनी दवाइयां ली हैं?",
    "checkin.yes": "हाँ",
    "checkin.no": "नहीं",
    "checkin.stepsCount": "कदमों की गिनती",
    "checkin.enterSteps": "आज के कदमों की संख्या दर्ज करें",
    "checkin.steps": "कदम",
    "checkin.stressLevel": "तनाव का स्तर",
    "checkin.howStressed": "आप कितना तनाव महसूस कर रहे हैं?",
    "checkin.low": "कम",
    "checkin.moderate": "मध्यम",
    "checkin.high": "उच्च",
    "checkin.veryHigh": "बहुत उच्च",
    "checkin.next": "आगे",
    "checkin.back": "पीछे",
    "checkin.complete": "पूरा करें",
    "checkin.completedSuccess": "दिनचर्या पूरी हुई!",
    "checkin.startMorning": "सुबह का चेक-इन शुरू करें",
    "checkin.startEvening": "शाम का चेक-इन शुरू करें",
    "checkin.readingAutoFilled": "रीडिंग अपने-आप भर गई!",
    "checkin.morningComplete": "सुबह का चेक-इन पूरा हुआ! 🎉",
    "checkin.eveningComplete": "शाम का चेक-इन पूरा हुआ! 🎉",
    "checkin.failed": "चेक-इन विफल हुआ",
    "checkin.saveFailed": "डेटा सेव नहीं हो सका। कृपया दोबारा कोशिश करें।",
    "checkin.sugarRangeError": "शुगर रीडिंग 20 से 600 mg/dL के बीच होनी चाहिए",
    "checkin.stepsRangeError": "कदमों की संख्या 0 से 100,000 के बीच होनी चाहिए",
    "checkin.autoFillPhoto": "फोटो से ऑटो-भरें",
    "checkin.bpPhotoHelp": "BP मॉनिटर की फोटो लें",
    "checkin.orManual": "या मैन्युअली दर्ज करें",
    "checkin.systolicShort": "सिस्टोलिक",
    "checkin.diastolicShort": "डायस्टोलिक",
    "checkin.heartRateOptional": "हृदय गति (वैकल्पिक)",
    "checkin.fastingBloodSugar": "फास्टिंग शुगर",
    "checkin.scan": "स्कैन",
    "checkin.sleepQuestion": "आपकी नींद कैसी रही?",
    "checkin.feelingQuestion": "आप कैसा महसूस कर रहे हैं?",
    "checkin.socialConnection": "सामाजिक जुड़ाव",
    "checkin.connectedQuestion": "आप कितना जुड़ा हुआ महसूस कर रहे हैं?",
    "checkin.talkedQuestion": "क्या आपने परिवार या दोस्तों से बात की?",
    "checkin.lonelyQuestion": "अकेलापन महसूस हो रहा है?",
    "checkin.outsideQuestion": "क्या आप आज बाहर गए?",
    "checkin.morningMedsQuestion": "सुबह की दवाइयां?",
    "checkin.eveningMedsQuestion": "शाम की दवाइयां?",
    "checkin.notYet": "अभी नहीं",
    "checkin.notesToday": "आज के लिए कोई नोट?",
    "checkin.notesTodaySubtitle": "वैकल्पिक - कोई विचार जोड़ें",
    "checkin.notesTodayPlaceholder": "आज आप कैसा महसूस कर रहे हैं?",
    "checkin.notesDay": "आज के दिन के बारे में कोई नोट?",
    "checkin.notesDaySubtitle": "वैकल्पिक - अपने दिन पर विचार लिखें",
    "checkin.notesDayPlaceholder": "आपका दिन कैसा रहा?",
    "checkin.morningTitle": "सुबह का चेक-इन",
    "checkin.eveningTitle": "शाम का चेक-इन",
    "checkin.enterBpOptional": "अपनी BP रीडिंग दर्ज करें (वैकल्पिक)",
    "checkin.enterSugarOptional": "अपनी शुगर रीडिंग दर्ज करें (वैकल्पिक)",
    "checkin.lonelyNotAtAll": "बिल्कुल नहीं",
    "checkin.lonelyALittle": "थोड़ा",
    "checkin.lonelySomewhat": "कुछ हद तक",
    "checkin.lonelyVery": "बहुत",
    "checkin.tryAgain": "कृपया दोबारा कोशिश करें।",
    
    // AI Coach
    "coach.title": "बीट AI",
    "coach.subtitle": "आपका व्यक्तिगत स्वास्थ्य सलाहकार",
    "coach.placeholder": "अपने स्वास्थ्य के बारे में कुछ भी पूछें...",
    "coach.send": "भेजें",
    "coach.thinking": "सोच रहे हैं...",
    "coach.newChat": "नई चैट",
    "coach.disclaimer": "यह AI सलाह है, चिकित्सा निदान नहीं। गंभीर लक्षणों के लिए डॉक्टर से मिलें।",
    "coach.hello": "नमस्ते! मैं बीट हूं",
    "coach.askAnything": "अपने स्वास्थ्य के बारे में कोई भी सवाल पूछें।",
    
    // Common
    "common.loading": "लोड हो रहा है...",
    "common.save": "सेव करें",
    "common.cancel": "रद्द करें",
    "common.delete": "हटाएं",
    "common.edit": "संपादित करें",
    "common.close": "बंद करें",
    "common.success": "सफलता!",
    "common.error": "कुछ गलत हो गया",
    "common.retry": "दोबारा कोशिश करें",
    "common.remove": "हटाएं",
    "common.saving": "सेव हो रहा है...",
    "common.user": "यूज़र",
    "common.premium": "प्रीमियम",
    "common.days": "दिन",
    "common.reviews": "रिव्यू",
    "common.skip": "छोड़ें",
    "common.reset": "रीसेट",
    
    // Family
    "family.title": "परिवार डैशबोर्ड",
    "family.subtitle": "अपने प्रियजनों के स्वास्थ्य पर नज़र रखें",
    "family.addMember": "परिवार का सदस्य जोड़ें",
    "family.noMembers": "अभी तक कोई परिवार का सदस्य नहीं",
    "family.addFirst": "अपना पहला सदस्य जोड़ें",
    "family.relationship": "रिश्ता",
    "family.permissions": "अनुमतियां",
    "family.canView": "स्वास्थ्य डेटा देख सकते हैं",
    "family.canNudge": "नज़ भेज सकते हैं",
    
    // Onboarding
    "onboarding.welcome": "बीट में आपका स्वागत है!",
    "onboarding.subtitle": "अपना बीट मजबूत रखें",
    "onboarding.language": "अपनी भाषा चुनें",
    "onboarding.continue": "जारी रखें",
    "onboarding.basicInfo": "बुनियादी जानकारी",
    "onboarding.basicInfoDesc": "हमें अपने बारे में बताएं",
    "onboarding.fullName": "पूरा नाम",
    "onboarding.namePlaceholder": "अपना नाम दर्ज करें",
    "onboarding.dateOfBirth": "जन्म तिथि",
    "onboarding.gender": "लिंग",
    "onboarding.genderPlaceholder": "लिंग चुनें",
    "onboarding.male": "पुरुष",
    "onboarding.female": "महिला",
    "onboarding.other": "अन्य",
    "onboarding.height": "ऊंचाई (सेमी)",
    "onboarding.weight": "वजन (किग्रा)",
    "onboarding.healthGoals": "स्वास्थ्य लक्ष्य",
    "onboarding.healthGoalsDesc": "आप क्या ट्रैक करना चाहेंगे?",
    "onboarding.hasHypertension": "मुझे उच्च रक्तचाप है",
    "onboarding.hasDiabetes": "मुझे मधुमेह है",
    "onboarding.hasHeartDisease": "मुझे हृदय रोग है",
    "onboarding.ritualTimes": "दैनिक चेक-इन समय",
    "onboarding.ritualTimesDesc": "हमें आपको कब याद दिलाना चाहिए?",
    "onboarding.morningTime": "सुबह की चेक-इन",
    "onboarding.eveningTime": "शाम की चेक-इन",
    "onboarding.finish": "शुरू करें",
    "onboarding.success": "बीट में आपका स्वागत है!",
    "onboarding.error": "ऑनबोर्डिंग पूरी करने में विफल",
    
    // Insights
    "insights.title": "स्वास्थ्य इनसाइट्स",
    "insights.subtitle": "अपने स्वास्थ्य रुझान देखें",
    "insights.pdfReport": "PDF रिपोर्ट",
    "insights.avgBP": "औसत BP",
    "insights.avgSugar": "औसत शुगर",
    "insights.heartScore": "हार्टस्कोर",
    "insights.avgSteps": "औसत कदम",
    "insights.aiInsights": "AI स्वास्थ्य इनसाइट्स",
    "insights.personalized": "आपके स्वास्थ्य डेटा पर आधारित व्यक्तिगत विश्लेषण",
    "insights.heartScoreTrend": "हार्टस्कोर ट्रेंड (30 दिन)",
    "insights.bpTrend": "रक्तचाप ट्रेंड (30 दिन)",
    "insights.sugarTrend": "रक्त शर्करा ट्रेंड (30 दिन)",
    "insights.emptyHeartScore": "हार्टस्कोर ट्रेंड देखने के लिए रूटीन पूरे करें",
    "insights.emptyBp": "ट्रेंड देखने के लिए BP रीडिंग लॉग करें",
    "insights.emptySugar": "ट्रेंड देखने के लिए शुगर लेवल लॉग करें",
    
    // Challenges
    "challenges.title": "स्वास्थ्य चुनौतियां",
    "challenges.subtitle": "समुदाय के साथ मिलकर स्वस्थ आदतें बनाएं",
    "challenges.featured": "लोकप्रिय चुनौतियां",
    "challenges.myChallenges": "मेरी चुनौतियां",
    "challenges.allChallenges": "सभी चुनौतियां",
    "challenges.join": "शामिल हों",
    "challenges.leave": "छोड़ें",
    "challenges.joined": "शामिल",
    "challenges.daysLeft": "दिन बाकी",
    "challenges.participants": "प्रतिभागी",
    
    // Shop
    "shop.title": "स्वास्थ्य स्टोर",
    "shop.subtitle": "आपकी स्वास्थ्य यात्रा के लिए अनुशंसित उत्पाद",
    "shop.featured": "विशेष उत्पाद",
    "shop.viewProduct": "उत्पाद देखें",
    "shop.beatShop": "बीट शॉप",
    "shop.beatRecommended": "बीट द्वारा सुझाए गए स्वास्थ्य उत्पाद",
    "shop.buy": "खरीदें",
    "shop.membersDiscount": "बीट प्रीमियम सदस्यों को खास छूट मिलती है। आज ही अपग्रेड करें!",
    "shop.viewPremium": "प्रीमियम देखें →",
    "shop.badge.bestSeller": "सबसे ज्यादा बिकने वाला",
    "shop.badge.popular": "लोकप्रिय",
    "shop.badge.heartHealth": "दिल की सेहत",
    "shop.badge.topRated": "टॉप रेटेड",
    
    // Subscription
    "subscription.title": "बीट प्रीमियम",
    "subscription.subtitle": "अपनी पूरी स्वास्थ्य क्षमता अनलॉक करें",
    "subscription.free": "मुफ्त",
    "subscription.basic": "बेसिक",
    "subscription.premium": "प्रीमियम",
    "subscription.currentPlan": "वर्तमान प्लान",
    "subscription.upgrade": "अपग्रेड",
    "subscription.perMonth": "/महीना",
    
    // Profile
    "profile.title": "प्रोफ़ाइल",
    "profile.settings": "सेटिंग्स",
    "profile.notifications": "सूचनाएं",
    "profile.connectDevices": "डिवाइस कनेक्ट करें",
    "profile.exportData": "मेरा डेटा एक्सपोर्ट करें",
    "profile.deleteAccount": "अकाउंट हटाएं",
    "profile.signOut": "साइन आउट",
    "profile.backToDashboard": "डैशबोर्ड पर वापस जाएं",
    "profile.personalInfo": "व्यक्तिगत जानकारी",
    "profile.fullName": "पूरा नाम",
    "profile.phoneNumber": "फोन नंबर",
    "profile.weight": "वजन (किग्रा)",
    "profile.height": "ऊंचाई (सेमी)",
    "profile.dateOfBirth": "जन्म तिथि",
    "profile.gender": "लिंग",
    "profile.preferNotToSay": "नहीं बताना चाहते",
    "profile.female": "महिला",
    "profile.male": "पुरुष",
    "profile.nonBinary": "नॉन-बाइनरी",
    "profile.other": "अन्य",
    "profile.healthConditions": "स्वास्थ्य स्थितियां",
    "profile.diabetes": "डायबिटीज",
    "profile.hypertension": "हाई BP",
    "profile.heartDisease": "हृदय रोग",
    "profile.advancedMetrics": "एडवांस स्वास्थ्य मेट्रिक्स (वैकल्पिक)",
    "profile.smokingStatus": "धूम्रपान स्थिति",
    "profile.unknown": "पता नहीं",
    "profile.neverSmoked": "कभी धूम्रपान नहीं किया",
    "profile.formerSmoker": "पहले धूम्रपान करते थे",
    "profile.currentSmoker": "अभी धूम्रपान करते हैं",
    "profile.cholesterolRatio": "कोलेस्ट्रॉल रेशियो",
    "profile.lastHba1c": "आखिरी HbA1c (%)",
    "profile.advancedMetricsHelp": "ये मेट्रिक्स AI जोखिम अनुमान को बेहतर बनाते हैं। इन वैल्यूज़ के लिए अपने डॉक्टर से पूछें।",
    "profile.notificationPreferences": "नोटिफिकेशन सेटिंग्स",
    "profile.whatsappMessages": "WhatsApp मैसेज",
    "profile.whatsappMessagesDesc": "WhatsApp पर रोज़ाना रिमाइंडर",
    "profile.dailyReminders": "रोज़ाना रिमाइंडर",
    "profile.dailyRemindersDesc": "सुबह और शाम के चेक-इन रिमाइंडर",
    "profile.weeklySummary": "साप्ताहिक सारांश",
    "profile.weeklySummaryDesc": "साप्ताहिक स्वास्थ्य इनसाइट रिपोर्ट",
    "profile.upgradeToPremium": "प्रीमियम में अपग्रेड करें",
    "profile.premiumDescription": "बीट AI कोच, PDF रिपोर्ट, एडवांस इनसाइट्स और प्राथमिकता सपोर्ट अनलॉक करें।",
    "profile.upgradePremiumPrice": "प्रीमियम में अपग्रेड करें - ₹199/माह",
    "profile.dataPrivacy": "डेटा और प्राइवेसी",
    "profile.exportingData": "डेटा एक्सपोर्ट हो रहा है...",
    "profile.exportDialogTitle": "अपना Beat Health डेटा एक्सपोर्ट करें?",
    "profile.exportDialogDescription": "इससे आपकी प्रोफ़ाइल, BP लॉग, शुगर लॉग, चेक-इन लॉग और दवाइयों का JSON फ़ाइल बनेगा। Android पर Beat नेटिव शेयर शीट खोलेगा ताकि आप फ़ाइल को Files, Drive, Gmail या किसी और ऐप में सेव कर सकें। ब्राउज़र में beat-health-data-[date].json नाम से डाउनलोड शुरू होगा।",
    "profile.startExport": "एक्सपोर्ट शुरू करें",
    "profile.exporting": "एक्सपोर्ट हो रहा है...",
    "profile.exportFailed": "एक्सपोर्ट विफल हुआ",
    "profile.retryExport": "फिर से एक्सपोर्ट करें",
    "profile.deleteConfirmTitle": "क्या आप बिल्कुल निश्चित हैं?",
    "profile.deleteConfirmDescription": "यह कार्रवाई वापस नहीं की जा सकती। इससे आपका अकाउंट और आपका सारा स्वास्थ्य डेटा हमारे सर्वर से स्थायी रूप से हट जाएगा।",
    "profile.deleteAccountAction": "अकाउंट हटाएं",
    "profile.saveChanges": "बदलाव सेव करें",
    "profile.namePlaceholder": "अपना नाम दर्ज करें",
    "profile.saved": "प्रोफ़ाइल सेव हो गई",
    "profile.saveFailed": "प्रोफ़ाइल सेव नहीं हो सकी",
    "profile.loadFailed": "प्रोफ़ाइल लोड नहीं हो सकी",
    "profile.photoUpdated": "प्रोफ़ाइल फोटो अपडेट हो गई",
    "profile.photoUploadFailed": "फोटो अपलोड नहीं हो सकी",
    "profile.fileTooLarge": "फ़ाइल 2MB से कम होनी चाहिए",
    "profile.exportPreparing": "आपका JSON एक्सपोर्ट तैयार हो रहा है...",
    "profile.exportSignInRequired": "डेटा एक्सपोर्ट करने के लिए साइन इन करें।",
    "profile.exportOpeningShare": "JSON एक्सपोर्ट के लिए शेयर शीट खुल रही है...",
    "profile.exportShareTitle": "Beat Health डेटा एक्सपोर्ट",
    "profile.exportShareText": "आपका Beat Health डेटा एक्सपोर्ट JSON फ़ाइल के रूप में जुड़ा है।",
    "profile.exportShareDialog": "डेटा एक्सपोर्ट सेव या शेयर करें",
    "profile.exportNativeSuccess": "आपका डेटा एक्सपोर्ट तैयार है। इसे सेव करने के लिए शेयर शीट में Files, Drive, Gmail या कोई और ऐप चुनें।",
    "profile.exportBrowserSuccess": "आपका डेटा सफलतापूर्वक एक्सपोर्ट हो गया। JSON फ़ाइल का ब्राउज़र डाउनलोड शुरू हो गया है।",
    "profile.exportDismissed": "एक्सपोर्ट तैयार था, लेकिन शेयर शीट बंद कर दी गई। फ़ाइल सेव या शेयर करने के लिए फिर से एक्सपोर्ट शुरू करें।",
    "profile.exportFailedTryAgain": "डेटा एक्सपोर्ट नहीं हो सका। कृपया दोबारा कोशिश करें।",
    "profile.noActiveSession": "कोई सक्रिय सेशन नहीं मिला",
    "profile.accountDeleted": "अकाउंट सफलतापूर्वक हट गया",
    "profile.deleteFailed": "अकाउंट हटाया नहीं जा सका",

    // Medications
    "medications.title": "दवाइयां",
    "medications.subtitle": "अपनी दवाइयां मैनेज करें और नियमितता ट्रैक करें",
    "medications.loading": "दवाइयां लोड हो रही हैं...",
    "medications.add": "दवाई जोड़ें",
    "medications.addNew": "नई दवाई जोड़ें",
    "medications.name": "दवाई का नाम *",
    "medications.namePlaceholder": "जैसे, Aspirin",
    "medications.dosage": "डोज़",
    "medications.dosagePlaceholder": "जैसे, 100mg",
    "medications.frequency": "कब लेनी है",
    "medications.morningOnly": "सिर्फ सुबह",
    "medications.eveningOnly": "सिर्फ शाम",
    "medications.morningEvening": "सुबह और शाम",
    "medications.notes": "नोट्स",
    "medications.notesPlaceholder": "कोई खास निर्देश",
    "medications.adherenceRate": "नियमितता दर (पिछले 7 दिन)",
    "medications.takenOnTime": "दवाइयां समय पर ली गईं",
    "medications.noMedications": "अभी कोई दवाई नहीं जोड़ी गई",
    "medications.addFirst": "अपनी पहली दवाई जोड़ें",
    "medications.taken": "ली",
    "medications.skip": "छोड़ें",
    "medications.takenToday": "आज ली गई",
    "medications.dosagePrefix": "डोज़:",
    "medications.frequencyPrefix": "समय:",
    "medications.morning": "सुबह",
    "medications.evening": "शाम",
    "medications.adherenceProgress": "{taken} में से {total} दवाइयां समय पर ली गईं",

    // Dashboard details
    "dashboard.startMorningCheckin": "सुबह का चेक-इन शुरू करें",
    "dashboard.startEveningCheckin": "शाम का चेक-इन शुरू करें",
    "dashboard.smartCapture": "स्मार्ट कैप्चर",
    "dashboard.healthMonitoring": "हेल्थ मॉनिटरिंग",

    // Bottom navigation
    "nav.health": "सेहत",
    "nav.beat": "Beat",
    "nav.me": "मैं",

    // Activity tracker
    "activity.title": "एक्टिविटी ट्रैकर",
    "activity.subtitle": "अपनी गतिविधि ट्रैक करें और हेल्थ पॉइंट्स कमाएं",
    "activity.todayProgress": "आज की प्रगति",
    "activity.goalProgress": "लक्ष्य का {percent}%",
    "activity.steps": "कदम",
    "activity.calories": "कैलोरी",
    "activity.minutes": "मिनट",
    "activity.active": "चालू",
    "activity.paused": "रुका हुआ",
    "activity.pause": "रोकें",
    "activity.resume": "फिर शुरू करें",
    "activity.endSave": "समाप्त कर सेव करें",
    "activity.startActivity": "एक्टिविटी शुरू करें",
    "activity.walking": "वॉकिंग",
    "activity.running": "रनिंग",
    "activity.cycling": "साइक्लिंग",
    "activity.yoga": "योग",
    "activity.started": "{activity} सेशन शुरू हुआ!",
    "activity.saved": "एक्टिविटी सेव हो गई!",
    "activity.saveFailed": "एक्टिविटी सेव नहीं हो सकी",
    "activity.motionNote": "📱 कदम गिनना मोशन सेंसर वाले मोबाइल पर सबसे अच्छा काम करता है",
    "activity.tipsTitle": "💡 एक्टिविटी टिप्स",
    "activity.tipSteps": "• 10,000 कदम ≈ 5 मील ≈ 400-500 कैलोरी",
    "activity.tipBp": "• रोज़ 30 मिनट चलने से BP 4-9 mmHg तक कम हो सकता है",
    "activity.tipSugar": "• खाने के बाद टहलने से ब्लड शुगर स्पाइक कम हो सकते हैं",

    // Social wellness
    "social.title": "सामाजिक सेहत",
    "social.log": "लॉग करें",
    "social.logTitle": "सामाजिक गतिविधि लॉग करें",
    "social.interactionsToday": "आज की बातचीत",
    "social.moodToday": "आज आपका मूड कैसा है?",
    "social.connectedScale": "आप कितना जुड़ा महसूस कर रहे हैं? (1 = अकेला, 5 = बहुत जुड़ा)",
    "social.outsideToday": "क्या आप आज बाहर गए?",
    "social.notesOptional": "नोट्स (वैकल्पिक)",
    "social.notesPlaceholder": "आपका दिन कैसा रहा?",
    "social.interactions": "बातचीत",
    "social.daysOut": "बाहर गए दिन",
    "social.wellness": "सेहत",
    "social.loggedToday": "आज लॉग हो गया!",
    "social.notLoggedToday": "आज अभी लॉग नहीं किया",
    "social.suggested": "सुझाई गई गतिविधियां:",
    "social.logged": "सामाजिक सेहत लॉग हो गई!",
    "social.logFailed": "लॉग नहीं हो सका",
    "social.familyCall": "परिवार कॉल",
    "social.friendVisit": "दोस्त से मुलाकात",
    "social.communityEvent": "समुदाय कार्यक्रम",
    "social.religiousGathering": "मंदिर/मस्जिद/चर्च",
    "social.neighborChat": "पड़ोसी से बात",
    "social.videoCall": "वीडियो कॉल",
    "mood.low": "कम",
    "mood.belowAverage": "औसत से कम",
    "mood.neutral": "सामान्य",
    "mood.good": "अच्छा",
    "mood.great": "बहुत अच्छा",

    // Alerts
    "alerts.title": "स्वास्थ्य अलर्ट",
    "alerts.new": "नए",
    "alerts.allClear": "सब ठीक है!",
    "alerts.none": "अभी कोई स्वास्थ्य अलर्ट नहीं है। ऐसे ही जारी रखें!",
    "alerts.newAlerts": "नए अलर्ट",
    "alerts.urgent": "तुरंत",
    "alerts.important": "महत्वपूर्ण",
    "alerts.info": "जानकारी",
    "alerts.acknowledged": "अलर्ट स्वीकार किया गया",
    "alerts.ackFailed": "अलर्ट स्वीकार नहीं हो सका",
    "alerts.justNow": "अभी",
    "alerts.yesterday": "कल",
    "alerts.highBp": "हाई BP",
    "alerts.lowBp": "लो BP",
    "alerts.highSugar": "हाई शुगर",
    "alerts.lowSugar": "लो शुगर",
    "alerts.rapidChange": "तेज़ बदलाव",
    "alerts.missedCheckin": "छूटा चेक-इन",
    "alerts.medicationDue": "दवाई का समय",

    // Family permissions
    "family.managePermissions": "अनुमतियां मैनेज करें",
    "family.updatePermissions": "{name} के लिए रिश्ता और अनुमतियां अपडेट करें",
    "family.selectRelationship": "रिश्ता चुनें",
    "family.parent": "माता-पिता",
    "family.child": "बच्चा",
    "family.spouse": "पति/पत्नी",
    "family.sibling": "भाई-बहन",
    "family.grandparent": "दादा-दादी/नाना-नानी",
    "family.grandchild": "पोता-पोती/नाती-नातिन",
    "family.other": "अन्य",
    "family.accessPermissions": "एक्सेस अनुमतियां",
    "family.viewHealthData": "स्वास्थ्य डेटा देखें",
    "family.viewHealthDesc": "BP, शुगर, दवाइयां और स्वास्थ्य मेट्रिक्स देखने दें",
    "family.sendReminders": "रिमाइंडर भेजें",
    "family.sendRemindersDesc": "स्वास्थ्य रिमाइंडर और चेक-इन नज भेजने दें",
    "family.privacyNotice": "प्राइवेसी नोटिस:",
    "family.privacyNoticeText": "परिवार सदस्य केवल डेटा देख सकते हैं, बदल नहीं सकते। सुरक्षा के लिए सभी एक्सेस लॉग होते हैं।",

    // Agent settings/memory
    "agent.settings": "एजेंट सेटिंग्स",
    "agent.settingsDesc": "आपका AI एजेंट कैसे व्यवहार करे, यह नियंत्रित करें",
    "agent.autonomyLevel": "ऑटोनॉमी स्तर",
    "agent.minimal": "न्यूनतम",
    "agent.balanced": "संतुलित",
    "agent.full": "पूर्ण",
    "agent.minimalDesc": "एजेंट केवल देखेगा, कोई ऑटोमैटिक कार्रवाई नहीं",
    "agent.balancedDesc": "नज और सेलिब्रेशन, लक्ष्य बदलाव नहीं",
    "agent.fullDesc": "लक्ष्य बदलाव सहित पूरी ऑटोनॉमी",
    "agent.automaticActions": "ऑटोमैटिक कार्रवाइयां",
    "agent.autoNudges": "ऑटो नज",
    "agent.autoNudgesDesc": "सक्रिय स्वास्थ्य रिमाइंडर",
    "agent.autoCelebrations": "ऑटो सेलिब्रेशन",
    "agent.autoCelebrationsDesc": "उपलब्धियों की ऑटोमैटिक पहचान",
    "agent.autoGoalAdjustment": "ऑटो लक्ष्य बदलाव",
    "agent.autoGoalAdjustmentDesc": "प्रगति के आधार पर लक्ष्य अपने-आप बदलें",
    "agent.healthAlerts": "स्वास्थ्य अलर्ट",
    "agent.healthAlertsDesc": "चिंताजनक स्वास्थ्य पैटर्न पर अलर्ट बढ़ाएं",
    "agent.dailyLimits": "दैनिक सीमाएं",
    "agent.maxNudgesPerDay": "प्रति दिन अधिकतम नज",
    "agent.maxGoalAdjustmentsPerWeek": "प्रति सप्ताह अधिकतम लक्ष्य बदलाव",
    "agent.quietHours": "शांत समय",
    "agent.quietHoursDesc": "शांत समय में एजेंट गैर-ज़रूरी नोटिफिकेशन नहीं भेजेगा",
    "agent.from": "से",
    "agent.to": "तक",
    "agent.preferencesSaved": "एजेंट सेटिंग्स सेव हो गईं",
    "agent.preferencesFailed": "सेटिंग्स सेव नहीं हो सकीं",
    "agent.memory": "एजेंट मेमोरी",
    "agent.memoryDesc": "Beat आपके बारे में क्या याद रखता है",
    "agent.memories": "मेमोरी",
    "agent.engagementRate": "एंगेजमेंट दर",
    "agent.engaged": "एंगेज्ड",
    "agent.ignored": "नज़रअंदाज़",
    "agent.avgResponse": "औसत प्रतिक्रिया",
    "agent.whatBeatKnows": "Beat क्या जानता है",
    "agent.memoryCleared": "मेमोरी साफ़ हो गई",
    "agent.memoryClearFailed": "मेमोरी साफ़ नहीं हो सकी",
    "agent.primaryFocus": "आपका मुख्य फोकस {focus} ट्रैकिंग है",
    "agent.activeAround": "आप आमतौर पर {time} के आसपास ज़्यादा सक्रिय रहते हैं",
    "agent.engagementRateText": "आपकी एंगेजमेंट दर {rate}% है",
    "agent.nudgeFrequencyReduced": "आपकी पसंद के आधार पर नज की संख्या कम कर दी गई है",
    "agent.learnedPreferences": "सीखी गई पसंद",
    "agent.detectedPatterns": "पहचाने गए पैटर्न",
    "agent.knownFacts": "ज्ञात बातें",
    "agent.confident": "भरोसा",
    "agent.clearMemoryTitle": "यह मेमोरी साफ़ करें?",
    "agent.clearPatternTitle": "यह पैटर्न साफ़ करें?",
    "agent.clearFactTitle": "यह बात साफ़ करें?",
    "agent.clearMemoryDesc": "Beat \"{memory}\" भूल जाएगा और समय के साथ इसे फिर से सीख सकता है।",
    "agent.clearPatternDesc": "Beat यह पैटर्न भूल जाएगा और समय के साथ इसे फिर से सीख सकता है।",
    "agent.clearFactDesc": "Beat यह बात भूल जाएगा और समय के साथ इसे फिर से सीख सकता है।",
    "agent.clear": "साफ़ करें",
    "agent.stillLearning": "Beat अभी आपके बारे में सीख रहा है।",
    "agent.stillLearningDesc": "कुछ दिनों तक ऐप इस्तेमाल करें, फिर पैटर्न दिखने लगेंगे।",
    "devices.connectedDevices": "कनेक्टेड डिवाइस",
    "devices.addDevice": "डिवाइस जोड़ें",
    "devices.addNewDevice": "नया डिवाइस जोड़ें",
    "devices.deviceType": "डिवाइस प्रकार",
    "devices.selectDeviceType": "डिवाइस प्रकार चुनें",
    "devices.deviceNameOptional": "डिवाइस नाम (वैकल्पिक)",
    "devices.deviceNamePlaceholder": "जैसे, Omron BP Monitor, Ultrahuman CGM",
    "devices.noDevices": "कोई डिवाइस कनेक्ट नहीं है",
    "devices.noDevicesDesc": "रीडिंग ऑटो-सिंक करने के लिए अपना BP monitor, glucometer या smartwatch जोड़ें।",
    "devices.connected": "कनेक्टेड",
    "devices.pending": "पेंडिंग",
    "devices.neverSynced": "कभी सिंक नहीं हुआ",
    "devices.justNow": "अभी",
    "devices.minutesAgo": "{count} मिनट पहले",
    "devices.hoursAgo": "{count} घंटे पहले",
    "devices.comingSoon": "जल्द आ रहा है:",
    "devices.comingSoonDesc": "Health Connect (Android) और Apple Health (iOS) के साथ ऑटो-सिंक। अभी के लिए, पेयरिंग के बाद डिवाइस को \"कनेक्टेड\" मार्क करें और मैनुअल एंट्री इस्तेमाल करें।",
    "devices.loadFailed": "कनेक्टेड डिवाइस लोड नहीं हो सके",
    "devices.selectTypeError": "कृपया डिवाइस प्रकार चुनें",
    "devices.added": "डिवाइस जुड़ गया! पेयर होने के बाद इसे कनेक्टेड मार्क करें।",
    "devices.addFailed": "डिवाइस जोड़ा नहीं जा सका",
    "devices.connectedToast": "डिवाइस कनेक्ट हो गया!",
    "devices.disconnectedToast": "डिवाइस डिसकनेक्ट हो गया",
    "devices.updateFailed": "डिवाइस अपडेट नहीं हो सका",
    "devices.connectFirst": "पहले डिवाइस कनेक्ट करें",
    "devices.syncComplete": "सिंक पूरा हुआ! डेटा इंपोर्ट हो गया।",
    "devices.syncFailed": "सिंक नहीं हो सका",
    "devices.removed": "डिवाइस हटा दिया गया",
    "devices.removeFailed": "डिवाइस हटाया नहीं जा सका",
    "devices.healthConnect": "Health Connect (Android)",
    "devices.appleHealth": "Apple Health (iOS)",
    "devices.smartwatch": "Smartwatch / Band",
    "devices.bpMonitor": "BP Monitor",
    "devices.glucometer": "Glucometer",
    "devices.cgm": "CGM Device",
    "devices.manualEntry": "मैनुअल एंट्री",
    "labs.title": "लैब रिज़ल्ट",
    "labs.add": "जोड़ें",
    "labs.addResult": "लैब रिज़ल्ट जोड़ें",
    "labs.testType": "टेस्ट प्रकार",
    "labs.selectTest": "टेस्ट चुनें",
    "labs.testDate": "टेस्ट तारीख",
    "labs.value": "वैल्यू",
    "labs.normal": "सामान्य",
    "labs.labNameOptional": "लैब नाम (वैकल्पिक)",
    "labs.labNamePlaceholder": "जैसे, Apollo Diagnostics",
    "labs.saveResult": "रिज़ल्ट सेव करें",
    "labs.testsDueSoon": "टेस्ट जल्द देय हैं",
    "labs.daysOverdue": "{count} दिन लेट",
    "labs.inDays": "{count} दिन में",
    "labs.noResultsYet": "अभी कोई रिज़ल्ट नहीं",
    "labs.outsideNormalRange": "सामान्य रेंज से बाहर",
    "labs.noLabResults": "अभी कोई लैब रिज़ल्ट नहीं",
    "labs.noLabResultsDesc": "ट्रैकिंग शुरू करने के लिए पहला रिज़ल्ट जोड़ें",
    "labs.resultAdded": "लैब रिज़ल्ट जुड़ गया",
    "labs.addFailed": "रिज़ल्ट जोड़ा नहीं जा सका",

    // HeartScore explanation
    "heartScore.infoAria": "HeartScore कैसे कैलकुलेट होता है?",
    "heartScore.infoTitle": "HeartScore कैसे कैलकुलेट होता है?",
    "heartScore.infoIntro": "आपका HeartScore आपकी रोज़ाना स्वास्थ्य आदतों और मापों के आधार पर कैलकुलेट होता है।",
    "heartScore.factorsTitle": "यह इन बातों को ध्यान में रखता है:",
    "heartScore.factorBp": "• Blood Pressure",
    "heartScore.factorSugar": "• Blood Sugar",
    "heartScore.factorCheckins": "• रोज़ाना चेक-इन और नियमितता",
    "heartScore.factorSleep": "• नींद और लाइफस्टाइल आदतें",
    "heartScore.factorSocial": "• सामाजिक जुड़ाव",
    "heartScore.factorEnvironment": "• पर्यावरण से जुड़े कारक (जब उपलब्ध हों)",
    "heartScore.factorCognitive": "• कॉग्निटिव असेसमेंट (जब उपलब्ध हों)",
    "heartScore.infoUpdates": "नया स्वास्थ्य डेटा रिकॉर्ड होने पर स्कोर अपडेट होता है।",
    "heartScore.infoMissing": "डेटा कम होने पर स्कोर की सटीकता घट सकती है।",
    "heartScore.infoHigher": "आम तौर पर ज्यादा स्कोर बेहतर रोज़ाना स्वास्थ्य आदतों को दिखाता है।",
    "heartScore.infoMedical": "यह स्कोर समय के साथ ट्रेंड समझने में मदद करता है और मेडिकल सलाह की जगह नहीं लेता।",
    "heartScore.improveTitle": "HeartScore बेहतर करने के लिए:",
    "heartScore.improveCheckins": "✓ रोज़ाना चेक-इन पूरा करें",
    "heartScore.improveLogs": "✓ BP और Sugar नियमित रूप से लॉग करें",
    "heartScore.improveHabits": "✓ स्वस्थ लाइफस्टाइल आदतें अपनाएं",
    "heartScore.snapshot": "आज की स्वास्थ्य झलक",
    "heartScore.fair": "ठीक",
    "heartScore.critical": "गंभीर",
    "heartScore.bp": "BP",
    "heartScore.sugar": "Sugar",
    "heartScore.ritual": "रूटीन",
    "heartScore.completeRitual": "HeartScore कैलकुलेट करने के लिए रूटीन पूरा करें",
    "heartScore.calculate": "स्कोर कैलकुलेट करें",
    "heartScore.calculating": "कैलकुलेट हो रहा है...",

    // Device capture / OCR
    "deviceCapture.smartCapture": "स्मार्ट कैप्चर",
    "deviceCapture.scanBp": "BP स्कैन करें",
    "deviceCapture.scanSugar": "Sugar स्कैन करें",
    "deviceCapture.heartRate": "हार्ट रेट",
    "deviceCapture.scanDeviceScreen": "डिवाइस स्क्रीन स्कैन करें",
    "deviceCapture.loginFirst": "पहले लॉग इन करें",
    "deviceCapture.saveFailed": "रीडिंग सेव नहीं हो सकी",
    "deviceCapture.bpSaved": "BP {value} सेव हो गया!",
    "deviceCapture.sugarSaved": "Blood sugar {value} mg/dL सेव हो गई!",
    "deviceCapture.hrRecorded": "हार्ट रेट {value} bpm रिकॉर्ड हो गया!",
    "deviceCapture.scanDevice": "डिवाइस स्कैन करें",
    "deviceCapture.bpMonitor": "BP मॉनिटर",
    "deviceCapture.glucoseMeter": "शुगर मीटर",
    "deviceCapture.pulseOximeter": "ऑक्सीमीटर",
    "deviceCapture.anyDevice": "कोई भी डिवाइस",
    "deviceCapture.fileTooLarge": "फ़ाइल बहुत बड़ी है (max 10MB)",
    "deviceCapture.photoReadFailed": "फोटो पढ़ी नहीं जा सकी। कृपया दूसरी फोटो लेकर दोबारा प्रयास करें।",
    "deviceCapture.unableToRead": "{device} पढ़ा नहीं जा सका। कृपया साफ़ फोटो लें और दोबारा प्रयास करें।",
    "deviceCapture.detectedReading": "पहचानी गई रीडिंग",
    "deviceCapture.confidence": "विश्वास स्तर",
    "deviceCapture.retry": "दोबारा",
    "deviceCapture.useThis": "इस्तेमाल करें",
    "deviceCapture.openCamera": "कैमरा खोलें",
    "deviceCapture.scanTitle": "{device} स्कैन करें",
    "deviceCapture.scanDescription": "डिवाइस स्क्रीन की फोटो लें",
    "deviceCapture.noReadings": "कोई रीडिंग नहीं मिली",
    "deviceCapture.readingSaved": "रीडिंग सेव हो गई!"
  }
};

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined);
const LANGUAGE_STORAGE_KEY = "beat-language";

const isLanguage = (value: unknown): value is Language => value === "en" || value === "hi";

const getStoredLanguage = (): Language => {
  if (typeof window === "undefined") return "en";
  const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return isLanguage(stored) ? stored : "en";
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = React.useState<Language>(getStoredLanguage);
  const profileSyncSkippedRef = React.useRef(false);

  const setLanguage = React.useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  React.useEffect(() => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);

    if (!profileSyncSkippedRef.current) {
      profileSyncSkippedRef.current = true;
      return;
    }

    let cancelled = false;

    const syncProfileLanguage = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user || cancelled) return;

      const { error } = await supabase
        .from("profiles")
        .update({ language })
        .eq("id", user.id);

      if (error) {
        console.error("Failed to sync profile language", error);
      }
    };

    syncProfileLanguage();

    return () => {
      cancelled = true;
    };
  }, [language]);

  React.useEffect(() => {
    let cancelled = false;

    const restoreProfileLanguage = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user || cancelled) return;

      const { data, error } = await supabase
        .from("profiles")
        .select("language")
        .eq("id", user.id)
        .maybeSingle();

      if (error) {
        console.error("Failed to restore profile language", error);
        return;
      }

      if (isLanguage(data?.language) && !cancelled) {
        setLanguage(data.language);
      }
    };

    restoreProfileLanguage();

    const { data: authListener } = supabase.auth.onAuthStateChange((_event, session) => {
      const profileLanguage = session?.user?.user_metadata?.language;
      if (isLanguage(profileLanguage)) {
        setLanguage(profileLanguage);
        return;
      }

      restoreProfileLanguage();
    });

    return () => {
      cancelled = true;
      authListener.subscription.unsubscribe();
    };
  }, [setLanguage]);

  const t = React.useCallback((key: string, values?: Record<string, string | number>): string => {
    const template = translations[language][key as keyof typeof translations.en] || key;
    if (!values) return template;

    return Object.entries(values).reduce(
      (message, [name, value]) => message.replace(new RegExp(`\\{${name}\\}`, "g"), String(value)),
      template
    );
  }, [language]);

  const value = React.useMemo(
    () => ({ language, setLanguage, t }),
    [language, setLanguage, t]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
